import { Simulation } from './src/simulation/simulation.js';
const sim = new Simulation(4242);
let t0 = process.hrtime.bigint();
for (let i = 0; i < 500; i++) sim.tick();
let t1 = process.hrtime.bigint();
console.log('first 500 ticks ms:', Number(t1 - t0) / 1e6, 'agents:', sim.agents.length);
t0 = process.hrtime.bigint();
for (let i = 0; i < 500; i++) sim.tick();
t1 = process.hrtime.bigint();
console.log('ticks 500-1000 ms:', Number(t1 - t0) / 1e6, 'agents:', sim.agents.length);
t0 = process.hrtime.bigint();
for (let i = 0; i < 500; i++) sim.tick();
t1 = process.hrtime.bigint();
console.log('ticks 1000-1500 ms:', Number(t1 - t0) / 1e6, 'agents:', sim.agents.length);
